language: android

jdk: oraclejdk8

before_install:
  # Download SDK
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "build-tools;27.0.3" &>/dev/null
  - yes | sdkmanager "platforms;android-27" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null

script: ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "MzOFFRAE6bEO5NzGQBFQ1am0lHwbsWqRdP/OTL/Ka/QgjryIETiLZdNUua23DwcJMuiMKVR0I03lqW5PCF0yT1+R8KECncF1P61YrHtATr0KhfXJ/z3DcqtxsBJ4gtVEJfuBXCgdHyYbMmS6UJVMgejCqv4YKYQggtOe/wgNm0PjwPOEQ7aktz47yEUbQOr9jxNwYDLNGzbgc9oBt+rFFYY+EfcbLQrrfq6sMyioc9c8UqNESRcAgapptwnywofd1fbgSvZ1kYpwD9scPcFgZFiG7KzNyxU0/GL2ojAT3buZFYKEToAFLTKFdHJTzwMMlUOMFoW4FB/aMlObvCcaguuMhkoD8ApaJg9Y3YLTkUzBDc6AvIvg4MwoujP6NawJJZEinG1EtuKc577WtXIpaA700s+m/go/Bsel27TUIFWnPQiPUyuyUoHvd/1xI2d1EWKZjudeaHTIhv5N8Y1W3Lb2AriSZ2ijK22I4QnrikDv1iWTaPYr8EGJbOOp4ifldLEpBJZSk8Eqv40ow5nSPNc8wmQ5Zd38wgp/qY0ZBgVOtKAUzi4t6K2hyTr7gIZ1fKyhYrIZuQFluLnQAzHQcNZM/Hlf5c9DS6tdJhSYBFbqzSlZ7UL3E98+3MZ9Bc15Z8HTlGrw1NTbLrAgpmE12PJN+oBR5U+Hay5VOJIpu+w="
    - secure: "rhhkm3u4m9kZuDJQAtGIEW8kvwIb25bDnBJgmMR7HwCZhju1TT9nfe7kK630dj4fdVfyb9yBxHsdVRxyz8OeqxHMh0GfanJNs0rAH9aqIwXfGc8Qv7kFq9fjKojRIObvRR/0N/gJ2WXwmat7iM8AtUvNtj/hTXEcl1dd3Th9inLbuG57eS/5jT4n9czJ8Wg9nZfHXePlCFTJDEnyvmatAHvkR3CsvzUVclXGQAvw2MGA6QqXOnPDGYKX2z5scePsU0awOg0q2+H2zs2wHsyZnIf2Jn/gngWF8ij2GcVSxreX7hDBAaBhcm6KXejr81WT9sQaMCQUfFZhEo2+P86f0p2JkW1gub9h7VUQhMU1LZSHhFEWBfuNAYN2iboRJOxp7lBcTQEup+3L3mFhdwQe4f5rHyTK1t7doj+4+SLQoOmyaoTLIdZzafeQzv6JYMuJRbtDsTWSzPMzMtjzBBBC2qzVNuHiXxypNTjeOAJKDNwn5YhubTro5z5KeuM1D8/gb1TKFXOpOBUu1SJPu5CeuaP6U9D/0rny6QL2bC114qJNLTnWqEHk58lIVC/sVrWd3uxWFph6rUUEM0wgC9Uz2y2iye8OauamgfN5RP7e2ETR0NnI9USik/KuKD1MhVMh8A3q2GyaMMTEFg20dhJP40hRntb0sUxv0DW/sqIWp9I="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
